// Every *.selftest.ts module registers itself on import. Later tasks add imports here.
import '../sky/sky.selftest';
import '../weather/clouds.selftest';
import '../ocean/fft.selftest';
import '../ocean/ocean.selftest';
import '../ocean/probe.selftest';
import '../ocean/underwater.selftest';
import '../seabed/seabed.selftest';
import '../seabed/seabedShading.selftest';
import '../seabed/kelp.selftest';
import '../seabed/kelpLook.selftest';
import '../breaker/breaker.selftest';
import '../breaker/ribbon.selftest';
import '../breaker/flow.selftest';
import '../whitewater/foamField.selftest';
import '../whitewater/spray.selftest';
import '../land/land.selftest';
import '../surf/surf.selftest';

export { renderSelfTestReport, runSelfTests } from './selfTest';
import '../beach/beach.selftest';
import '../heath/heath.selftest';
import '../bombie/bombie.selftest';
import '../board/board.selftest';
import '../surfer/grommet.selftest';
import '../surfer/face.selftest';
import '../surfer/hair.selftest';
import '../surfer/surfer.selftest';
import '../sound/sound.selftest';
import '../surfer/walking.selftest';
import '../frontend/frontEnd.selftest';
import '../frontend/surfMap.selftest';
import '../app/loading.selftest';
